[package]
name = "solana-foundation-delegation-program-registry"
version = "1.0.0"
edition = "2018"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
license = "Apache-2.0"

[dependencies]
borsh = "0.8"
borsh-derive = "0.9.0"
solana-program = "1.7.0"

[features]
test-bpf = []

[dev-dependencies]
assert_matches = "1.4.0"
solana-program-test = "1.7.0"
solana-sdk = "1.7.0"

[lib]
crate-type = ["cdylib", "lib"]
